//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextEntityFramework : DbContext
    {
        public ContextEntityFramework()
            : base("name=ContextEntityFramework")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<grade> grade { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<subject> subject { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<teacher_groups> teacher_groups { get; set; }
    }
}
