//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighWayToHell
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        public int id { get; set; }
        public int studentId { get; set; }
        public int courseId { get; set; }
        public int teacherId { get; set; }
        public int grade1 { get; set; }
        public byte[] timestamp { get; set; }
    }
}
